
try {
    console.log(a);
} catch (error) {
    console.log(error);
} finally {
    console.log("Finally block");
}

console.log("Hello World");
console.log(10 + 20);